# Generated by Django 5.1.1 on 2024-09-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='toa',
        ),
        migrations.RemoveField(
            model_name='table',
            name='btype',
        ),
        migrations.RemoveField(
            model_name='table',
            name='spp',
        ),
    ]
