# Generated by Django 5.1.1 on 2024-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_name_table_toa_remove_table_btype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='br',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='colu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='fco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='fund',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='nat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='nop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='rp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='sco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
