# Generated by Django 5.1.1 on 2024-09-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_table_br_table_colu_table_date_table_dept_table_fco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='toa',
            new_name='Title_of_activity',
        ),
    ]
